services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns_Estudio
    env_file:
      - duckdns.env
    volumes:
      - ./duckdns:/config #optional
    restart: unless-stopped