services:
  nextcloud:
    image: nextcloud:production
    container_name: nextcloud
    env_file:
      - config.env
    volumes:
      - ./nextcloud/config:/var/www/html/config # Configuracion de nextcloud
      - ./nextcloud/data:/var/www/html/data # Datos de nextcloud
    ports:
      - 8081:80 #Puertos de acceso a la interfaz web. El primero es el puerto de la maquina host, el segundo es el puerto del contenedor
    depends_on:
      - mariadb
    restart: unless-stopped
  

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    env_file:
      - config.env
    volumes:
      - ./mariadb/config:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
    restart: unless-stopped
