services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
