services:

  mailserver:
    image: analogic/poste.io
    container_name: mailserver-sysbeards
    restart: always
    # network_mode: "host"
    # expose:
    #   - "25"
    #   - "8080"
    #   - "4443"
    #   - "110"
    #   - "143"
    #   - "465"
    #   - "587"
    #   - "993"
    #   - "995"
    ports:
      - "25:25"
      - "8080:8080"
      - "4443:4443"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - h=mail.tudominio.com # Direccion del servidor de mail hosting
      - HTTP_PORT=8080
      - HTTPS_PORT=4443
      - DISABLE_CLAMAV=TRUE
    volumes:
      - ./mail:/data