version: "3"

services:
 
  BaseDeDatos:
    image: linuxserver/mariadb:10.11.5
    container_name: BaseDeDatosTest
    env_file:
      - mariadb.env
    volumes:
      - ./MariaDB:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    env_file:
      - duckdns.env
    #volumes:
    #  - ./duckdns:/config #optional
    restart: unless-stopped
