services:

  mysql:
      image: mysql:5.7
      container_name: mysql
      env_file: MySQL.env
      volumes:
        - ./datos:/var/lib/mysql
      ports:
        - "3306:3306"
      restart: always