version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name:  postgres-DB
    ports:
      - 5432:5432
    volumes:
      - ./postgresData:/var/lib/postgresql/data
    env_file:
      - postgres.env
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: postgres-duckdns
    env_file:
      - duckdns.env
    #volumes:
    #  - ./duckdns:/config #optional
    restart: unless-stopped
