services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum_core
    env_file:
      - flarum.env
    volumes:
      - ./root/dt-applications/flarum/assets:/flarum/app/public/assets
      - ./root/dt-applications/flarum/extensions:/flarum/app/extensions
      - ./root/dt-applications/flarum/storage/logs:/flarum/app/storage/logs
      - ./root/dt-applications/flarum/nginx:/etc/nginx/flarum
    ports:
      - 8888:8888
    depends_on:
      - flarummariadb


  flarummariadb:
    image: mysql:5.7
    container_name: flarum_mariadb
    env_file:
      - DB.env
    volumes:
      - ./root/dt-applications/flarum/mysql:/var/lib/mysql